import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI(
    api_key= os.getenv("GEMINI_API_key"),
    # direct way to add api key is 
    # api_key="GEMINI_API_KEY",
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)


# response → variable where we store the AI's response
# client → our connection/client used to communicate with the API
# chat.completions → tells the API that we want the model to generate a chat response
# .create() → sends the request to the AI and creates the response
response = client.chat.completions.create(
    model="gemini-3.8-flash",
    reasoning_effort="low",
    messages=[
        {   "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Explain to me how AI works in 20 words"
        }
    ]
)

# response → the complete response received from the API.
# .choices → accesses the list of generated response choices.
# [0] → selects the first choice from that list.
# .message → accesses the message inside that choice.
# .content → gets the actual text generated by the AI.
print(response.choices[0].message.content)